services:
  # https://hub.docker.com/_/nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www:rw,delegated
      - ./docker/nginx/conf.d/symfony.conf:/etc/nginx/conf.d/symfony.conf:ro
      - ./logs/nginx:/var/log/nginx:rw,delegated
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - php
    restart: unless-stopped
    tty: true
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.rick-and-morty-api.loadbalancer.server.port: 80

      # allow http trafic on dev server
      traefik.http.routers.rick-and-morty-api-http.entrypoints: web
      traefik.http.routers.rick-and-morty-api-http.rule: Host(`dev.rick-and-morty-api.localhost`) || Host(`dev-rick-and-morty-api.tangoman.io`)

      # redirect http trafic to https on prod server
      traefik.http.routers.rick-and-morty-api-redirect.entrypoints: web
      traefik.http.routers.rick-and-morty-api-redirect.rule: Host(`rick-and-morty-api.localhost`) || Host(`dev-rick-and-morty-api.tangoman.io`)
      traefik.http.routers.rick-and-morty-api-redirect.middlewares: redirect-https@file

      # https configuration
      traefik.http.routers.rick-and-morty-api-https.entrypoints: websecure
      traefik.http.routers.rick-and-morty-api-https.rule: Host(`rick-and-morty-api.localhost`) || Host(`rick-and-morty-api.tangoman.io`)
      traefik.http.routers.rick-and-morty-api-https.middlewares: security@file, compression@file
      traefik.http.routers.rick-and-morty-api-https.tls: true

  php:
    build:
      context: ./docker/php/
      dockerfile: php8.2-fpm-alpine-prod.Dockerfile
    volumes:
      - ./:/var/www:rw,delegated
      - ./docker/php/conf.d/symfony-prod.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ~/.ssh:/root/.ssh:ro
    restart: unless-stopped
    tty: true
    networks:
      - traefik

networks:
  traefik:
    external: true
